module.exports=(sequelize,DataTypes)=>{
    const User=sequelize.define("users",{
        email:{
            type:DataTypes.STRING,
            allowNull:false,
            unique:true,
            isEmail:true,
        },
        password:{
            type:DataTypes.STRING,
            allowNull:false,
        },
        role:{
            type:DataTypes.STRING,
            allowNull:false,
        },
        firstName:{
            type:DataTypes.STRING,
            allowNull:false,
        },
        lastName:{
            type:DataTypes.STRING,
        },
        gender:{
            type:DataTypes.STRING,
            allowNull:false,
        },
        photo:{
            type:DataTypes.TEXT,
        },
    });
    return User
}